### ISSUE TITLE
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

### ISSUE THREAD

**Issue by RadZaeem** [docker-scripts/mariadb#4]
In the latest commit (transfer apt install code to Dockerfile), I tried to use it to install mariadb container with `ds make`, and got this error when I try to run mysql cli client
```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```
The previous commit works fine (tested with dbox ds container)

**Comment by dashohoxha** [comment]
Thanks for reporting it. I had tried it by reinstalling an existing container, and in this case there was no problem. It is fixed by #5.
